repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
      exclude: ^.*\b(migrations)\b.*$

  -   repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: name-tests-test
        args: [ '--django' ]
      - id: debug-statements
      - id: no-commit-to-branch
        args: [ --branch, main ]
